const LoginConstants = {
  EMAIL_VALID,
  EMAIL_INVALID: 'EMAIL_INVALID',
  PASSWORD_VALID: 'PASSWORD_VALID',
  PASSWORD_INVALID: 'PASSWORD_INVALID',
  LOGGED_IN: 'LOGGED_IN'
};

module.exports = LoginConstants;
